# Generated by Django 5.2.17 on 2026-08-23 20:17

import apps.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobLineTransition",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("action_code", models.TextField()),
                (
                    "performed_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "job line transition",
                "db_table": "pipeline_job_line_transitions",
                "ordering": ["-performed_at", "-id"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", apps.core.fields.CITextField()),
                ("name", models.TextField()),
                (
                    "module_code",
                    models.TextField(
                        help_text="One conveyor per module. Appendix C uses 'JOB' for the whole sales-to-dispatch pipeline."
                    ),
                ),
                (
                    "sequence_no",
                    models.IntegerField(
                        help_text="Linear order, with wide gaps so departments can be inserted later without renumbering."
                    ),
                ),
                ("is_initial", models.BooleanField(db_default=False, default=False)),
                ("is_terminal", models.BooleanField(db_default=False, default=False)),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "verbose_name": "stage",
                "db_table": "pipeline_stages",
                "ordering": ["module_code", "sequence_no"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TransitionRule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_code", models.TextField()),
                (
                    "allow_self_approval",
                    models.BooleanField(
                        db_default=True,
                        default=True,
                        help_text="FALSE enforces the two-person rule: whoever moved the line into this stage may not move it out (D4).",
                    ),
                ),
                ("requires_note", models.BooleanField(db_default=False, default=False)),
                (
                    "condition_expr",
                    models.TextField(
                        blank=True,
                        help_text="Evaluated by a sandboxed allowlist parser at transition time. Never eval(). Restrict write access to this column.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "verbose_name": "transition rule",
                "db_table": "pipeline_transition_rules",
                "default_permissions": (),
            },
        ),
    ]
