# Generated by Django 5.2.17 on 2026-08-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("identity", "0001_initial"),
        ("pipeline", "0001_initial"),
        ("sales", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="joblinetransition",
            name="job_line",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transitions",
                to="sales.jobline",
            ),
        ),
        migrations.AddField(
            model_name="joblinetransition",
            name="performed_by",
            field=models.ForeignKey(
                db_column="performed_by",
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transitions_performed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stages",
                to="core.department",
            ),
        ),
        migrations.AddField(
            model_name="joblinetransition",
            name="from_stage",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transitions_from",
                to="pipeline.stage",
            ),
        ),
        migrations.AddField(
            model_name="joblinetransition",
            name="to_stage",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transitions_to",
                to="pipeline.stage",
            ),
        ),
        migrations.AddField(
            model_name="transitionrule",
            name="allowed_role",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transition_rules",
                to="identity.role",
            ),
        ),
        migrations.AddField(
            model_name="transitionrule",
            name="from_stage",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outgoing_rules",
                to="pipeline.stage",
            ),
        ),
        migrations.AddField(
            model_name="transitionrule",
            name="to_stage",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incoming_rules",
                to="pipeline.stage",
            ),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(fields=["department"], name="idx_stages_department"),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(fields=("code",), name="uk_stages_code"),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                fields=("module_code", "sequence_no"), name="uk_stages_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence_no__gt", 0)), name="ck_stages_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_initial", True), ("is_terminal", True), _negated=True
                ),
                name="ck_stages_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="stage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_initial", True), ("is_active", True)),
                fields=("module_code",),
                name="uk_stages_one_initial",
            ),
        ),
        migrations.AddIndex(
            model_name="joblinetransition",
            index=models.Index(
                fields=["job_line", "-performed_at"],
                name="idx_job_line_transitions_line",
            ),
        ),
        migrations.AddIndex(
            model_name="transitionrule",
            index=models.Index(fields=["from_stage"], name="idx_transition_rules_from"),
        ),
        migrations.AddIndex(
            model_name="transitionrule",
            index=models.Index(fields=["to_stage"], name="idx_transition_rules_to"),
        ),
        migrations.AddIndex(
            model_name="transitionrule",
            index=models.Index(
                fields=["allowed_role"], name="idx_transition_rules_role"
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionrule",
            constraint=models.UniqueConstraint(
                fields=("from_stage", "action_code", "allowed_role"),
                name="uk_transition_rules",
            ),
        ),
        migrations.AddConstraint(
            model_name="transitionrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_stage", models.F("to_stage")), _negated=True),
                name="ck_transition_rules_loop",
            ),
        ),
    ]
