# Generated by Django 5.2.17 on 2026-08-23 20:17

import apps.core.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_code", apps.core.fields.CITextField()),
                ("full_name", models.TextField()),
                ("date_of_joining", models.DateField()),
                ("date_of_exit", models.DateField(blank=True, null=True)),
                (
                    "employment_status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("on_notice", "On notice"),
                            ("exited", "Exited"),
                            ("suspended", "Suspended"),
                        ],
                        db_default="active",
                        default="active",
                    ),
                ),
                ("personal_phone", models.TextField(blank=True, null=True)),
                ("personal_email", apps.core.fields.CITextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="core.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="core.designation",
                    ),
                ),
                (
                    "photo_document",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_photos",
                        to="core.document",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "employee",
                "db_table": "hr_employees",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.TextField(
                        choices=[
                            ("id_proof", "ID proof"),
                            ("address_proof", "Address proof"),
                            ("qualification", "Qualification"),
                            ("appointment_letter", "Appointment letter"),
                            ("other", "Other"),
                        ]
                    ),
                ),
                ("is_sensitive", models.BooleanField(db_default=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_documents",
                        to="core.document",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "employee document",
                "db_table": "hr_employee_documents",
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["department"], name="idx_employees_department"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["designation"], name="idx_employees_designation"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["reports_to"], name="idx_employees_reports_to"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                condition=models.Q(
                    ("deleted_at__isnull", True), ("employment_status", "active")
                ),
                fields=["department"],
                name="idx_employees_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("employee_code",), name="uk_employees_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "employment_status__in",
                        ["active", "on_notice", "exited", "suspended"],
                    )
                ),
                name="ck_employees_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("date_of_exit__isnull", True),
                    ("date_of_exit__gte", models.F("date_of_joining")),
                    _connector="OR",
                ),
                name="ck_employees_exit_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(("reports_to", models.F("id")), _negated=True),
                name="ck_employees_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("personal_email__isnull", True),
                    (
                        "personal_email__regex",
                        "^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$",
                    ),
                    _connector="OR",
                ),
                name="ck_employees_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeedocument",
            constraint=models.UniqueConstraint(
                fields=("employee", "doc_type", "document"),
                name="uk_employee_documents",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "doc_type__in",
                        [
                            "id_proof",
                            "address_proof",
                            "qualification",
                            "appointment_letter",
                            "other",
                        ],
                    )
                ),
                name="ck_employee_documents_type",
            ),
        ),
    ]
