export const strings = {
  title: "Pipeline board",
  subtitle: "Every job line, in the stage it is actually in.",
  filterOwner: "Sales Rep",
  filterOwnerAll: "Everyone",
  filterOwnerMine: "Mine",
  filterClient: "Client",
  filterClientAll: "All clients",
  filterCategory: "Category",
  filterCategoryAll: "All categories",
  search: "Search",
  searchPlaceholder: "Job no, client, description",
  clearFilters: "Clear filters",
  emptyColumn: "Nothing here",
  emptyBoard: "No job lines match these filters.",
  stageSelector: "Stage",
  lineCount: (count: number) => `${count} ${count === 1 ? "line" : "lines"}`,
  openCard: "Open line",
  quotationRevision: (n: number) => `Rev ${n}`,
} as const;
