export const strings = {
  title: "Quotations",
  subtitle: "Revision chain, newest first.",
  empty: "No quotation has been uploaded for this card.",
  revision: (n: number) => `Rev ${n}`,
  superseded: "Superseded",
  validTill: "Valid till",
  amount: "Amount",
  covers: (count: number) => `${count} ${count === 1 ? "line" : "lines"}`,
  openPdf: "Open PDF",
  newRevision: "Upload revision",
  newRevisionTitle: "Upload quotation revision",
  file: "Quotation PDF",
  fileHint: "The PDF your quotation software produced. This system stores it, it does not make it.",
  amountLabel: "Quoted amount (₹)",
  amountHint: "Exactly as quoted, in rupees.",
  validTillLabel: "Valid till",
  coveredLines: "Lines this quotation covers",
  coveredLinesHint: "At least one. Lines not covered stay where they are.",
  supersedeNote: "Uploading creates the next revision and supersedes the current one.",
  submit: "Upload revision",
  submitting: "Uploading…",
  cancel: "Cancel",
  uploaded: (n: number) => `Revision ${n} uploaded`,
  uploadFailed: "The revision was not uploaded",
  fileRequired: "Choose the quotation PDF.",
  amountRequired: "Enter the quoted amount.",
  linesRequired: "Select at least one line.",
} as const;
