# Generated by Django 5.2.17 on 2026-08-23 20:17

import apps.core.fields
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # Ten columns are citext (deviation 3.1). Nothing below this line can
        # be created without the extension, so it is the very first operation
        # of the very first migration.
        CITextExtension(),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("occurred_at", models.DateTimeField()),
                ("table_schema", models.TextField()),
                ("table_name", models.TextField()),
                ("record_id", models.UUIDField(null=True)),
                (
                    "operation",
                    models.TextField(
                        choices=[
                            ("INSERT", "Insert"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ]
                    ),
                ),
                ("changed_by", models.UUIDField(null=True)),
                ("old_data", models.JSONField(null=True)),
                ("new_data", models.JSONField(null=True)),
            ],
            options={
                "verbose_name": "audit log entry",
                "verbose_name_plural": "audit log",
                "db_table": "core_audit_logs",
                "ordering": ["-occurred_at", "-id"],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("storage_key", models.TextField()),
                ("original_filename", models.TextField()),
                ("mime_type", models.TextField()),
                ("byte_size", models.BigIntegerField()),
                (
                    "sha256",
                    apps.core.fields.FixedCharField(
                        blank=True, max_length=64, null=True
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "db_table": "core_documents",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="NumberSeries",
            fields=[
                ("prefix", models.TextField(primary_key=True, serialize=False)),
                ("current", models.BigIntegerField(db_default=0, default=0)),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "number series",
                "verbose_name_plural": "number series",
                "db_table": "core_number_series",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", apps.core.fields.CITextField()),
                ("name", models.TextField()),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                (
                    "parent_department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="core.department",
                    ),
                ),
            ],
            options={
                "verbose_name": "department",
                "db_table": "core_departments",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", apps.core.fields.CITextField()),
                ("name", models.TextField()),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "verbose_name": "designation",
                "db_table": "core_designations",
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="uk_designations_code"
                    )
                ],
            },
        ),
    ]
