# Generated by Django 5.2.17 on 2026-08-23 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="uploaded_by",
            field=models.ForeignKey(
                db_column="uploaded_by",
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="numberseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("current__gte", 0)), name="ck_number_series_current"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["parent_department"], name="idx_departments_parent"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("code",), name="uk_departments_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("parent_department", models.F("id")), _negated=True
                ),
                name="ck_departments_not_self",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["uploaded_by"], name="idx_documents_uploaded_by"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                fields=("storage_key",), name="uk_documents_storage_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(("byte_size__gt", 0)), name="ck_documents_byte_size"
            ),
        ),
        migrations.AddConstraint(
            model_name="document",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sha256__isnull", True),
                    ("sha256__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="ck_documents_sha256",
            ),
        ),
    ]
