export const strings = {
  listTitle: "Job cards",
  listSubtitle: "Enquiries and the lines they split into.",
  newEnquiry: "New enquiry",
  filterOwner: "Owner",
  filterOwnerMine: "Mine",
  filterOwnerAll: "Everyone",
  filterStatus: "Status",
  filterStatusAll: "Any status",
  filterClient: "Client",
  filterClientAll: "All clients",
  search: "Search",
  searchPlaceholder: "Job no, title, client",
  emptyList: "No job cards match these filters.",
  emptyListMine: "Nothing open assigned to you.",

  colJobNo: "Job no",
  colClient: "Client",
  colTitle: "Title",
  colStatus: "Status",
  colLines: "Lines",
  colQuoted: "Quoted",
  colRequiredBy: "Required by",
  colUpdated: "Updated",
  colOwner: "Owner",
  colLine: "Line",
  colDescription: "Description",
  colCategory: "Category",
  colQty: "Qty",
  colStage: "Stage",
  colActions: "Moves",

  detailLines: "Job lines",
  detailNotes: "Notes",
  detailAttachments: "Attachments",
  detailQuotations: "Quotations",
  detailHeader: "Enquiry",
  print: "Print job card",
  addNote: "Add note",
  notePlaceholder: "Add a note for whoever picks this up next",
  noteEmpty: "No notes yet.",
  attachmentEmpty: "Nothing attached.",
  attachmentAdd: "Attach a file",
  attachmentUploading: "Uploading…",
  attachmentRemove: "Remove",
  attachmentRemoving: "Removing…",
  attachmentRemoveTitle: "Remove attachment",
  attachmentRemoveConfirm: "Yes, remove",
  attachmentRemoveBody: (filename: string) =>
    `Remove ${filename}? This only removes it from the card — the file itself isn't deleted.`,
  attachmentRemoved: (filename: string) => `${filename} removed`,
  linesEmpty: "This card has no lines yet.",

  intakeTitle: "New enquiry",
  intakeSubtitle: "One card, one or more lines. Lines move independently after this.",
  client: "Client",
  clientPlaceholder: "Search clients by name or code",
  clientCreate: "Add client",
  clientCreateLegalName: "Legal name",
  clientCreateSubmit: "Add client",
  clientCreateCancel: "Cancel",
  contact: "Contact",
  contactNone: "No contact",
  contactCreate: "Add contact",
  contactCreateSubmit: "Save contact",
  contactCreateCancel: "Cancel",
  contactCreateName: "Contact name",
  contactCreateNameRequired: "A contact name is required.",
  contactCreatePhone: "Phone",
  contactCreateEmail: "Email",
  contactCreateReachRequired: "Add a phone number or an email.",
  contactCreatePrimary: "Primary contact",
  title: "Title",
  titlePlaceholder: "What the client asked for, in a line",
  source: "Source",
  sourceNone: "Not recorded",
  enquiryDate: "Enquiry date",
  requiredBy: "Required by",
  dispatchPolicy: "Dispatch policy",
  dispatchPolicyNone: "Not set",
  requirements: "Requirements",
  requirementsHint:
    "Extra details specific to this enquiry, as a name and a value — for example, Voltage and 415V.",
  requirementKey: "Name",
  requirementValue: "Value",
  addRequirement: "Add requirement",
  removeRequirement: "Remove requirement",
  lines: "Job lines",
  addLine: "Add line",
  removeLine: "Remove line",
  lineDescription: "Description",
  lineCategory: "Category",
  lineCategoryNone: "Not categorised",
  lineQty: "Quantity",
  lineUom: "Unit",
  save: "Create enquiry",
  saving: "Creating…",
  cancel: "Cancel",
  createdToast: (jobNo: string) => `${jobNo} created`,
  createFailed: "The enquiry was not created",
  clientRequired: "Choose a client, or add one.",
  titleRequired: "A title is required.",
  lineDescriptionRequired: "Every line needs a description.",
} as const;
