export const strings = {
  listTitle: "Clients",
  listSubtitle: "Who the enquiries come from.",
  search: "Search",
  searchPlaceholder: "Name, code, city",
  activeOnly: "Active only",
  showAll: "All clients",
  empty: "No clients match this search.",
  colCode: "Code",
  colName: "Name",
  colCity: "City",
  colState: "State",
  colGstin: "GSTIN",
  colOpenJobs: "Open jobs",
  colStatus: "Status",
  active: "Active",
  inactive: "Inactive",

  detailContacts: "Contacts",
  detailJobs: "Job history",
  detailProfile: "Client",
  contactName: "Name",
  contactDesignation: "Designation",
  contactPhone: "Phone",
  contactEmail: "Email",
  contactPrimary: "Primary",
  makePrimary: "Make primary",
  promoting: "Updating…",
  promoted: "Primary contact updated",
  promoteFailed: "The primary contact was not changed",
  contactsEmpty: "No contacts recorded.",
  jobsEmpty: "No job cards for this client yet.",
  defaultDispatch: "Default dispatch policy",
  notSet: "Not set",
  address: "Address",
  gstin: "GSTIN",
  addedOn: "On file since",
} as const;
