# Generated by Django 5.2.17 on 2026-08-23 20:17

import apps.core.fields
import django.db.models.deletion
import django.db.models.functions.datetime
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_code", apps.core.fields.CITextField()),
                ("legal_name", models.TextField()),
                (
                    "gstin",
                    apps.core.fields.FixedCharField(
                        blank=True, max_length=15, null=True
                    ),
                ),
                ("billing_city", models.TextField(blank=True, null=True)),
                ("billing_state", models.TextField(blank=True, null=True)),
                (
                    "default_dispatch_policy",
                    models.TextField(
                        choices=[
                            ("partial_allowed", "Partial dispatch allowed"),
                            ("complete_only", "Complete order only"),
                        ],
                        db_default="partial_allowed",
                        default="partial_allowed",
                        help_text="Copied onto each new job card at creation. Changing it later does not touch existing cards.",
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "client",
                "db_table": "sales_clients",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("contact_name", models.TextField()),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", apps.core.fields.CITextField(blank=True, null=True)),
                ("is_primary", models.BooleanField(db_default=False, default=False)),
                (
                    "client",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="sales.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "client contact",
                "db_table": "sales_client_contacts",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_no",
                    models.TextField(
                        help_text="Issued by core.next_number(). Never reused."
                    ),
                ),
                (
                    "lifecycle_status",
                    models.TextField(
                        choices=[
                            ("open", "Open"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="open",
                        default="open",
                    ),
                ),
                (
                    "enquiry_source",
                    models.TextField(
                        choices=[
                            ("indiamart", "IndiaMART"),
                            ("website", "Website"),
                            ("phone", "Phone"),
                            ("referral", "Referral"),
                            ("walk_in", "Walk-in"),
                            ("other", "Other"),
                        ],
                        db_default="other",
                        default="other",
                    ),
                ),
                (
                    "dispatch_policy",
                    models.TextField(
                        choices=[
                            ("partial_allowed", "Partial dispatch allowed"),
                            ("complete_only", "Complete order only"),
                        ],
                        db_default="partial_allowed",
                        default="partial_allowed",
                        help_text="Seeded from the client default at creation, overridable per order, and change-tracked by the audit trigger on this table.",
                    ),
                ),
                (
                    "enquiry_date",
                    models.DateField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
                ("required_by", models.DateField(blank=True, null=True)),
                (
                    "requirements",
                    models.JSONField(blank=True, db_default={}, default=dict),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_cards",
                        to="sales.client",
                    ),
                ),
                (
                    "client_contact",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_cards",
                        to="sales.clientcontact",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        help_text="The sales rep. Attribution lives here, not inside job_no.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_job_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "job card",
                "db_table": "sales_job_cards",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="JobLine",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("line_no", models.SmallIntegerField()),
                ("description", models.TextField()),
                ("quantity", models.IntegerField(db_default=1, default=1)),
                (
                    "line_status",
                    models.TextField(
                        choices=[
                            ("active", "Active"),
                            ("on_hold", "On hold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="active",
                        default="active",
                    ),
                ),
                ("required_by", models.DateField(blank=True, null=True)),
                ("specs", models.JSONField(blank=True, db_default={}, default=dict)),
                (
                    "current_stage",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        help_text="Denormalised cache of the latest transition. Written only by the apply_transition() trigger — never assign it from Python.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_lines",
                        to="pipeline.stage",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.jobcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "job line",
                "db_table": "sales_job_lines",
                "ordering": ["job_card", "line_no"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="JobAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.TextField(blank=True, null=True)),
                (
                    "attached_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "attached_by",
                    models.ForeignKey(
                        db_column="attached_by",
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_attachments",
                        to="core.document",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="sales.jobcard",
                    ),
                ),
                (
                    "job_line",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="sales.jobline",
                    ),
                ),
            ],
            options={
                "verbose_name": "job attachment",
                "db_table": "sales_job_attachments",
                "ordering": ["-attached_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="JobNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="sales.jobcard",
                    ),
                ),
                (
                    "job_line",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="sales.jobline",
                    ),
                ),
            ],
            options={
                "verbose_name": "job note",
                "db_table": "sales_job_notes",
                "ordering": ["-created_at"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", apps.core.fields.CITextField()),
                ("name", models.TextField()),
                ("is_manufactured", models.BooleanField(db_default=True, default=True)),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "verbose_name": "product category",
                "verbose_name_plural": "product categories",
                "db_table": "sales_product_categories",
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="uk_product_categories_code"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="jobline",
            name="product_category",
            field=models.ForeignKey(
                db_constraint=False,
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_lines",
                to="sales.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quotation_no", models.TextField()),
                ("revision_no", models.SmallIntegerField(db_default=0, default=0)),
                (
                    "status",
                    models.TextField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("sent", "Sent"),
                            ("superseded", "Superseded"),
                            ("accepted", "Accepted"),
                            ("lost", "Lost"),
                        ],
                        db_default="draft",
                        default="draft",
                    ),
                ),
                (
                    "quoted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "currency",
                    apps.core.fields.FixedCharField(
                        db_default="INR", default="INR", max_length=3
                    ),
                ),
                ("valid_till", models.DateField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="sales.jobcard",
                    ),
                ),
                (
                    "pdf_document",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations",
                        to="core.document",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        db_column="prepared_by",
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_prepared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="sent_by",
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="sales.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "quotation",
                "db_table": "sales_quotations",
                "ordering": ["job_card", "revision_no"],
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "quotation_id",
                        "job_line_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "line_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "job_line",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines",
                        to="sales.jobline",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.quotation",
                    ),
                ),
            ],
            options={
                "verbose_name": "quotation line",
                "db_table": "sales_quotation_lines",
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("client_code",), name="uk_clients_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("gstin",), name="uk_clients_gstin"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "default_dispatch_policy__in",
                        ["partial_allowed", "complete_only"],
                    )
                ),
                name="ck_clients_dispatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gstin__isnull", True),
                    ("gstin__regex", "^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]{3}$"),
                    _connector="OR",
                ),
                name="ck_clients_gstin",
            ),
        ),
        migrations.AddIndex(
            model_name="clientcontact",
            index=models.Index(fields=["client"], name="idx_client_contacts_client"),
        ),
        migrations.AddConstraint(
            model_name="clientcontact",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("phone__isnull", False), ("email__isnull", False), _connector="OR"
                ),
                name="ck_client_contacts_reach",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientcontact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("deleted_at__isnull", True)),
                fields=("client",),
                name="uk_client_contacts_primary",
            ),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(fields=["client"], name="idx_job_cards_client"),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(fields=["owner_user"], name="idx_job_cards_owner"),
        ),
        migrations.AddIndex(
            model_name="jobcard",
            index=models.Index(
                condition=models.Q(
                    ("deleted_at__isnull", True),
                    ("lifecycle_status__in", ["open", "quoted"]),
                ),
                fields=["owner_user", "-enquiry_date"],
                name="idx_job_cards_open",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobcard",
            constraint=models.UniqueConstraint(
                fields=("job_no",), name="uk_job_cards_job_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "lifecycle_status__in",
                        ["open", "quoted", "won", "lost", "cancelled"],
                    )
                ),
                name="ck_job_cards_lifecycle",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("dispatch_policy__in", ["partial_allowed", "complete_only"])
                ),
                name="ck_job_cards_dispatch",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "enquiry_source__in",
                        [
                            "indiamart",
                            "website",
                            "phone",
                            "referral",
                            "walk_in",
                            "other",
                        ],
                    )
                ),
                name="ck_job_cards_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobcard",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("required_by__isnull", True),
                    ("required_by__gte", models.F("enquiry_date")),
                    _connector="OR",
                ),
                name="ck_job_cards_required",
            ),
        ),
        migrations.AddIndex(
            model_name="jobattachment",
            index=models.Index(fields=["job_card"], name="idx_job_attachments_card"),
        ),
        migrations.AddConstraint(
            model_name="jobattachment",
            constraint=models.UniqueConstraint(
                fields=("job_card", "document"), name="uk_job_attachments"
            ),
        ),
        migrations.AddIndex(
            model_name="jobnote",
            index=models.Index(
                fields=["job_card", "-created_at"], name="idx_job_notes_job_card"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobnote",
            constraint=models.CheckConstraint(
                condition=models.Q(("body__regex", "^\\s*$"), _negated=True),
                name="ck_job_notes_body",
            ),
        ),
        migrations.AddIndex(
            model_name="jobline",
            index=models.Index(fields=["job_card"], name="idx_job_lines_job_card"),
        ),
        migrations.AddIndex(
            model_name="jobline",
            index=models.Index(
                fields=["product_category"], name="idx_job_lines_category"
            ),
        ),
        migrations.AddIndex(
            model_name="jobline",
            index=models.Index(
                fields=["current_stage"], name="idx_job_lines_current_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobline",
            constraint=models.UniqueConstraint(
                fields=("job_card", "line_no"), name="uk_job_lines_line_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="ck_job_lines_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="jobline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("line_status__in", ["active", "on_hold", "completed", "cancelled"])
                ),
                name="ck_job_lines_status",
            ),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(fields=["job_card"], name="idx_quotations_job_card"),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("quotation_no",), name="uk_quotations_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("job_card", "revision_no"), name="uk_quotations_revision"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                fields=("supersedes",), name="uk_quotations_supersedes"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "active", "sent", "superseded", "accepted", "lost"],
                    )
                ),
                name="ck_quotations_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision_no__gte", 0)),
                name="ck_quotations_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quoted_amount__isnull", True),
                    ("quoted_amount__gte", 0),
                    _connector="OR",
                ),
                name="ck_quotations_amount",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["draft", "active"]), ("sent_at__isnull", True)
                    ),
                    models.Q(("sent_at__isnull", False), ("sent_by__isnull", False)),
                    ("status", "superseded"),
                    _connector="OR",
                ),
                name="ck_quotations_sent",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "draft"),
                    ("pdf_document__isnull", False),
                    _connector="OR",
                ),
                name="ck_quotations_pdf_needed",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("job_card",),
                name="uk_quotations_one_active",
            ),
        ),
        migrations.AddIndex(
            model_name="quotationline",
            index=models.Index(fields=["job_line"], name="idx_quotation_lines_line"),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("line_amount__isnull", True),
                    ("line_amount__gte", 0),
                    _connector="OR",
                ),
                name="ck_quotation_lines_amt",
            ),
        ),
    ]
