# Generated by Django 5.2.17 on 2026-08-23 20:17

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", apps.core.fields.CITextField()),
                ("password", models.TextField(db_column="password_hash")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, db_column="last_login_at", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
                (
                    "must_change_password",
                    models.BooleanField(db_default=True, default=True),
                ),
                ("password_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "failed_login_count",
                    models.SmallIntegerField(db_default=0, default=0),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        help_text="NOT NULL: every login belongs to exactly one employee.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_account",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "user account",
                "db_table": "auth_user_accounts",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="LoginSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("refresh_token_hash", models.TextField()),
                (
                    "issued_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "login session",
                "db_table": "auth_sessions",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resource", models.TextField()),
                (
                    "action",
                    models.TextField(
                        choices=[
                            ("view", "View"),
                            ("create", "Create"),
                            ("edit", "Edit"),
                            ("delete", "Delete"),
                            ("submit", "Submit"),
                            ("cancel", "Cancel"),
                            ("approve", "Approve"),
                            ("release", "Release"),
                            ("export", "Export"),
                            ("print", "Print"),
                            ("share", "Share"),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
            ],
            options={
                "verbose_name": "permission",
                "db_table": "auth_permissions",
                "ordering": ["resource", "action"],
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "action"),
                        name="uk_permissions_resource_action",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                [
                                    "view",
                                    "create",
                                    "edit",
                                    "delete",
                                    "submit",
                                    "cancel",
                                    "approve",
                                    "release",
                                    "export",
                                    "print",
                                    "share",
                                ],
                            )
                        ),
                        name="ck_permissions_action",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", apps.core.fields.CITextField()),
                ("name", models.TextField()),
                (
                    "is_system",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Seeded by a migration. Deleting one breaks the permission grid.",
                    ),
                ),
                ("is_active", models.BooleanField(db_default=True, default=True)),
            ],
            options={
                "verbose_name": "role",
                "db_table": "auth_roles",
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(fields=("code",), name="uk_roles_code")
                ],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "perm_level",
                    models.SmallIntegerField(
                        db_default=0,
                        default=0,
                        help_text="0 = ordinary fields, 1 = protected employee fields, 2 = sensitive documents (Appendix B).",
                    ),
                ),
                (
                    "if_owner",
                    models.BooleanField(
                        db_default=False,
                        default=False,
                        help_text="Grant applies only to rows the user owns.",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="identity.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="identity.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "role permission",
                "db_table": "auth_role_permissions",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=apps.core.fields.RandomUUID(),
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        db_default=apps.core.fields.Now(), editable=False
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="assigned_by",
                        db_constraint=False,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="identity.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_constraint=False,
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "role assignment",
                "db_table": "auth_user_roles",
                "default_permissions": (),
            },
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.UniqueConstraint(
                fields=("username",), name="uk_user_accounts_username"
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.UniqueConstraint(
                fields=("employee",), name="uk_user_accounts_employee"
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("username__length__gte", 3), ("username__length__lte", 64)
                ),
                name="ck_user_accounts_username",
            ),
        ),
        migrations.AddConstraint(
            model_name="useraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("failed_login_count__gte", 0)),
                name="ck_user_accounts_failed",
            ),
        ),
        migrations.AddIndex(
            model_name="loginsession",
            index=models.Index(fields=["user"], name="idx_sessions_user"),
        ),
        migrations.AddConstraint(
            model_name="loginsession",
            constraint=models.UniqueConstraint(
                fields=("refresh_token_hash",), name="uk_sessions_token"
            ),
        ),
        migrations.AddConstraint(
            model_name="loginsession",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("issued_at"))),
                name="ck_sessions_expiry",
            ),
        ),
        migrations.AddIndex(
            model_name="rolepermission",
            index=models.Index(fields=["permission"], name="idx_role_permissions_perm"),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.UniqueConstraint(
                fields=("role", "permission", "perm_level"), name="uk_role_permissions"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolepermission",
            constraint=models.CheckConstraint(
                condition=models.Q(("perm_level__gte", 0), ("perm_level__lte", 9)),
                name="ck_role_permissions_level",
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="idx_user_roles_role"),
        ),
        migrations.AddConstraint(
            model_name="userrole",
            constraint=models.UniqueConstraint(
                fields=("user", "role"), name="uk_user_roles"
            ),
        ),
    ]
